#!/usr/bin/env php
<?php

include __DIR__ . '/vendor/autoload.php';

$config = json_decode(file_get_contents(__DIR__ . '/housekeeper.json'), true);

$runner = new \Aigletter\HouseKeeper\HouseKeeper($config);

$runner->run();